version: '3'

services:
  mysql:
    image: mysql
    container_name: local-mysql-database
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass123

volumes:
  mysql:
